### ISSUE TITLE
Web development training

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/Intern#12]
@AsadUllahBinTahir 

I have bought an online course:

https://www.udemy.com/the-web-developer-bootcamp/

You should have received an invite for it.

Please start learning 

This should not take you more then 2 weeks.

**Comment by AsadUllahBinTahir** [comment]
@jekram : Acknowledged!

**Comment by jekram** [comment]
@AsadUllahBinTahir 

I talked to @sojharo already and it would be better that you do this before AngularJS 2

**Comment by AsadUllahBinTahir** [comment]
Okay, I would do it after the Web Training course.

**Comment by jekram** [comment]
Thanks

**Comment by AsadUllahBinTahir** [comment]
I have started the Web Developer Boot Camp course. Currently I have reached in Section 3 Basic Tags. Most of the concepts are not new to me and are just a revision.

**Comment by jekram** [comment]
Great - then you can expidite it

**Comment by jekram** [comment]
@AsadUllahBinTahir 

Please let me know what % of this training is complete

**Comment by AsadUllahBinTahir** [comment]
@jekram : My exams just finished on 29 of February. However, I have completed 6 sections and currently in 7th section - Bootstrap.

**Comment by AsadUllahBinTahir** [comment]
@jekram : Last night i worked on my web training (Udemy course) and did testing with @ImranBinShoukat & @sojharo. I also looked up for WordPress themes for the blog which I am supposed to set up.

**Comment by jekram** [comment]
Thanks for the update. at % of training is left?

**Comment by jekram** [comment]
Also please provide status in their own task - Like the blog work. It is easy to track by each task.

**Comment by AsadUllahBinTahir** [comment]
Sir It was 24% and I will be careful while providing status next time.

**Comment by AsadUllahBinTahir** [comment]
Today I continued my web course training. I have completed 34% of the course.

**Comment by jekram** [comment]
Good

**Comment by jekram** [comment]
No problem on the status. It just makes it easier for me. :-)

**Comment by jekram** [comment]
@AsadUllahBinTahir 

Let's target to finish this by March 19th

**Comment by AsadUllahBinTahir** [comment]
@jekram 
IA, I will finish it before March 19th

**Comment by AsadUllahBinTahir** [comment]
Today I continued my web training. I have completed 46% of the course. I am hopeful to finish it around 19th of March.

**Comment by jekram** [comment]
Good progress. Thanks for the update.

**Comment by AsadUllahBinTahir** [comment]
Today I completed 59% of the course.

**Comment by AsadUllahBinTahir** [comment]
Today I completed 81% of the Course.

**Comment by jekram** [comment]
Thanks for the update. Excellent progress.

**Comment by AsadUllahBinTahir** [comment]
Today I studied some more sections of web course. I am now at 87%.

**Comment by jekram** [comment]
Great job. Thanks for the update.

**Comment by AsadUllahBinTahir** [comment]
I have completed the web course except the Git section. I will end the course by completing the git section tomorrow.

**Comment by jekram** [comment]
@AsadUllahBinTahir 

Good Job. Keep me posted.

@sojharo

**Comment by jekram** [comment]
Status please

**Comment by AsadUllahBinTahir** [comment]
I have finished the course

**Comment by jekram** [comment]
Thanks - Great Job. When task are complete please put the final status and mark them resolved.

That is a flag for to close it.
