### ISSUE TITLE
Web Development training 

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/Intern#13]
I have bought an online course:

https://www.udemy.com/the-web-developer-bootcamp/

You should have received an invite for it.

Please start this course after WordPresss training is finished

This should not take you more than two weeks.

**Comment by ImranBinShoukat** [comment]
Acknowledged.

**Comment by jekram** [comment]
@ImranBinShoukat 

I talked to @sojharo already and it would be better that you do this before AngularJS 2

**Comment by ImranBinShoukat** [comment]
I have started the Web Developer Boot Camp course and I have completed the first three sections. I am hopeful that this would be a really good addition to skill set.

**Comment by jekram** [comment]
Thanks for the update

**Comment by jekram** [comment]
@ImranBinShoukat 

Please let me know what % of this training is complete

**Comment by ImranBinShoukat** [comment]
@jekram 

I have completed the section: 6 and will start the section: 7 tomorrow.

**Comment by jekram** [comment]
Thanks. BTW: How many ections are there?

**Comment by ImranBinShoukat** [comment]
38 sections

**Comment by ImranBinShoukat** [comment]
Today, I have completed the section: 7 and now I am in section: 8.

**Comment by jekram** [comment]
@ImranBinShoukat  Let's target to finish this by March 19Th.

**Comment by ImranBinShoukat** [comment]
Sure. I'll finish it by March 19th.

**Comment by ImranBinShoukat** [comment]
I have completed the 55% of the course.

**Comment by jekram** [comment]
Great. Look like you are on target. Thanks for the update.

**Comment by ImranBinShoukat** [comment]
Today, I continued my web development training and completed the 75% of the course.

**Comment by jekram** [comment]
Fantastic :+1:

**Comment by ImranBinShoukat** [comment]
I have completed the 85% of the course.

**Comment by jekram** [comment]
Great job. Thanks for the update

**Comment by jekram** [comment]
@ImranBinShoukat  What is the status of this?

**Comment by ImranBinShoukat** [comment]
I have almost completed the course just two sections are left, which I'll complete by tonight.

**Comment by jekram** [comment]
Thanks for thebupdate

**Comment by ImranBinShoukat** [comment]
I have completed the web development course.

**Comment by jekram** [comment]
Thanks. I hope you learned something new and enjoyed the course.

**Comment by ImranBinShoukat** [comment]
Yes I really enjoyed the course and learnt a lot about web development especially about back end, jQuery and DOM manipulation. Before that I didn't have that much idea of these things which I have now. 
Thank you very much for this :)

**Comment by jekram** [comment]
great
