### ISSUE TITLE
Setup jawaidekram blog site

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/Intern#15]
@AsadUllahBinTahir 

Please setup http://jawaidekram.com/wp-login

I would use this for putting out blogs about technology. 

Look into the current templates and if I need to buy in a template please let me know.

I want it to look some thing like:  http://blog.shippable.com/ and http://www.rightscale.com/blog/

It needs the following features:

1.  Topic bar at the top (some think like)

![image](https://cloud.githubusercontent.com/assets/5336012/13194792/054e4f8c-d753-11e5-969f-db9bae6a7c44.png)

2. Body should look some thing like

![image](https://cloud.githubusercontent.com/assets/5336012/13194804/6697f112-d753-11e5-8f04-76744eff4741.png)

3. Right hand side

![image](https://cloud.githubusercontent.com/assets/5336012/13194824/f7cc3990-d753-11e5-9170-5589e23b5ce1.png)

4. Right hand side Tags like

![image](https://cloud.githubusercontent.com/assets/5336012/13194812/b012cfce-d753-11e5-9ed7-8c57a3a4a67b.png)

5. Right hand side blog dates

6. Right hand jawaid profile button

**Comment by AsadUllahBinTahir** [comment]
@jekram : My mid exams are starting at IBA Karachi. Exams would be finished in a week. I would complete the job in shortest possible time once the exams are finished. I hope this won't be a problem.

**Comment by jekram** [comment]
@AsadUllahBinTahir  Not a problem. Take care of your exams

**Comment by jekram** [comment]
@AsadUllahBinTahir  Any update on this?

**Comment by AsadUllahBinTahir** [comment]
@jekram 
I have not actually started work on this. I was looking for required theme. I will start this task from Monday. :)

**Comment by jekram** [comment]
I think there are free theme,. However, If we need to buy a theme please let me know.

**Comment by AsadUllahBinTahir** [comment]
Sure :)

**Comment by AsadUllahBinTahir** [comment]
@jekram : Sir What are the login credentials?

**Comment by jekram** [comment]
I have regenerated the credentials
user name: asad
password: WOi3jdU2&nns%y634U*Nnm2&
email:  asad@cloudkibo.com

Please change the password upon login

Let me know if you cannot login

**Comment by AsadUllahBinTahir** [comment]
https://www.competethemes.com/apex-live-demo/
https://zorendemo.wordpress.com/

Please review the themes. I will search for more themes if these are not as per requirement.

**Comment by AsadUllahBinTahir** [comment]
Once you select the theme, I will modify it according to needs. I am asking for just design review.
Mostly new blog themes are not static as you have attached.

**Comment by jekram** [comment]
@AsadUllahBinTahir 

Let's do apex

https://www.competethemes.com/apex-live-demo/

Question: If we decide to change the theme later. Does it mean a complete re-install or just minor tweaks?

**Comment by AsadUllahBinTahir** [comment]
We would have to reinstall the theme. Installing a theme is not a big issue. Its just a matter of 3 to 4 minutes. Actual thing is the additional tweaks to the theme to make it according to need.

**Comment by AsadUllahBinTahir** [comment]
Please guide me about the content which is to be added to blog i.e name of pages (names of topics in topic bar), blog name/tagline etc.

**Comment by jekram** [comment]
Ok. Thanks for the calarification

**Comment by jekram** [comment]
http://blog.shippable.com/is-the-public-cloud-safe

please take this as the first blog

**Comment by AsadUllahBinTahir** [comment]
@jekram : Sir, I have published the first blog (I was using my own ID, So my name is appearing as author name). 
We can add many categories and tags. Inclusion of categories would finish the need of topic bar. However, topic bar can be included by further addition of pages. 
Currently the blog supports:
1. Categories are there at the side (Topic bar can be made by addition of pages).
2. Subscription button.
3. Social media buttons.
4. Tag Cloud.
Please let me know if any changes are needed in blog :)

**Comment by jekram** [comment]
@AsadUllahBinTahir  I will review this and get back to you later today

**Comment by jekram** [comment]
@AsadUllahBinTahir Is this done?

**Comment by AsadUllahBinTahir** [comment]
I completed this and asked you to review the work. Please tell me if any changes are to be made.

**Comment by jekram** [comment]
Yes. Action was on my side. Nothing more needed here.

I will mark it closed.

Thanks
