### ISSUE TITLE
Update http://162.243.4.147/ with developer content

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/Intern#16]
@ImranBinShoukat 

Please update http://162.243.4.147/ with developer content 

https://www.cloudkibo.com/developers

**Comment by ImranBinShoukat** [comment]
@jekram 

I have updated the http://162.243.4.147/ with developers and contact us page.

**Comment by jekram** [comment]
@ImranBinShoukat 

When I click on any link on the developer tab the links are broken.

**Comment by ImranBinShoukat** [comment]
Sir click on the links after logging in. It will work properly then. I have made the pages private because if I making it public then it is going to add in the navigation bar. I have searched and tried to overcome this but I couldn't find any other options than making in private.

**Comment by jekram** [comment]
No problem make them public. We already have this information public.

**Comment by ImranBinShoukat** [comment]
Done.

**Comment by jekram** [comment]
Fantastic. I am going to close this.
