### ISSUE TITLE
Testing CloudKibo URL March 01  2016

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/Intern#17]
@ImranBinShoukat 

There was an issue with Clock that was impacting the performance. Please retest. 

This task is similar to task #14 

![image](https://cloud.githubusercontent.com/assets/5336012/13099945/a55fb312-d4ec-11e5-9c64-a055b767a213.png)

FYI to @zarmeen92 @sojharo

**Comment by ImranBinShoukat** [comment]
We have tested with 2 and 3 people. However, 4 people testing will be done by tomorrow.
Here is the update.

![2 march 2016](https://cloud.githubusercontent.com/assets/17005430/13463326/7f92bc48-e0ad-11e5-8268-6a94cd016f92.JPG)

**Comment by jekram** [comment]
Thanks for the update.

@Sojharo please review these results
