### ISSUE TITLE
Urgent: Test Cloudkibo URL March 10 

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/Intern#18]
@ImranBinShoukat 

There was an issue with Clock that was impacting the performance. Please ret

![image](https://cloud.githubusercontent.com/assets/5336012/13099945/a55fb312-d4ec-11e5-9c64-a055b767a213.png)

FYI to @zarmeen92 @sojharo @AsadUllahBinTahir

**Comment by ImranBinShoukat** [comment]
We have tested the 2 and 3 people conference and webmeeting testing while we'll do the 4 people testing on Sunday.

![11 march 2016](https://cloud.githubusercontent.com/assets/17005430/13710180/a4cb6ed2-e7d9-11e5-929b-b8b022b58ba1.JPG)

**Comment by jekram** [comment]
Thanks for the update.

@sojharo I am assuming this was after some of your changes?

**Comment by sojharo** [comment]
Yes, I think after adding of callstats.io

**Comment by jekram** [comment]
@sojharo Tell this to callstats.io folks :-) They would either fix it or guide us how to integrate their product.

**Comment by sojharo** [comment]
yes, we would tell them. I would do more test tomorrow as we added lots of improved logs today and tested many things in web meeting. Also, we improved some code of clock which was continuously running in background by mistake. we have discussed this on slack too.

**Comment by jekram** [comment]
@sojharo 
The clock has bitten us a number of times. If we have to remove it I am ok with it and then reintroduce it later.
Need your recommendation.

@zarmeen92
