### ISSUE TITLE
Urgent: Test Cloudkibo URL March 20

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/Intern#19]
@ImranBinShoukat 

Please retest:

1. In your testing please make sure one person is behind Proxy server (see @sojharo  for it).

2. Also add test iOS to /webmeeting please see @sumairasaeed for it. Only 1-1 session needs to be tested (Chrome to iOS)

![image](https://cloud.githubusercontent.com/assets/5336012/13099945/a55fb312-d4ec-11e5-9c64-a055b767a213.png)

FYI to @zarmeen92 @sojharo @AsadUllahBinTahir

**Comment by ImranBinShoukat** [comment]
@sojharo  said that he is working to resolve turn issue and we can't test with one person behind proxy today.

**Comment by jekram** [comment]
Thanks

**Comment by ImranBinShoukat** [comment]
![chrome to ios 25 march](https://cloud.githubusercontent.com/assets/17005430/14042953/b3c57d98-f2a0-11e5-96ed-fdd691bc57ca.JPG)

**Comment by ImranBinShoukat** [comment]
![25 march test](https://cloud.githubusercontent.com/assets/17005430/14045245/53fb0a30-f2ba-11e5-976d-5b36c10a307b.JPG)

**Comment by jekram** [comment]
Thanks @ImranBinShoukat
