### ISSUE TITLE
Learn React Native

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/Intern#22]
@AsadUllahBinTahir 

As a next step I would like you to learn React Native. React Native allows you to develop mobile applications on iOS and Android. React Native is from Facebook and is a very wonderful tool.

1. Here is the Website:  https://facebook.github.io/react/

Also, watch Videos on Youtube.

2. There is a Tutorial on React  Native on Udemy:  Building Apps with React Native

https://drive.google.com/drive/folders/0ByXJY8WVZm-NaFlBLTJXX2xqejQ

3. Here is a book on React Native.
https://drive.google.com/drive/folders/0ByXJY8WVZm-NZzRpQUI4d2NxX00

Deliverable:

Do all the sample examples on Udemy and in the book.

Target completion is April 15th or sooner.

**Comment by jekram** [comment]
@AsadUllahBinTahir t

I am going to block this task. I think it would be more prudent for you to learn the basic of ReactJS first before getting confused on React Native.

I will open a new task on ReactJS.

Copying @sojharo

**Comment by AsadUllahBinTahir** [comment]
Today I worked on Udemy course " Building Apps with React Native" and have covered 30/72 Videos so far.

**Comment by jekram** [comment]
Thanks for the update

**Comment by AsadUllahBinTahir** [comment]
I studied the chapter 3 of the Book 'Learning React-native.' I have also completed 40/72 videos of udemy course.

**Comment by jekram** [comment]
Thanks for the update. great Job.

**Comment by AsadUllahBinTahir** [comment]
Task done:

Chapter 4 (Learning React-native)
61/72 Videos (Udemy Course)

**Comment by jekram** [comment]
Thanks for the update

**Comment by AsadUllahBinTahir** [comment]
I studied chapter 5 only today.
I couldn't give much time today due to two extra make up classes at university. Moreover, i am also due to present a presentation in one of my course on 2nd May i.e. Monday. 
I will give extra hours on Monday night to complete my work (Which I skip today.)
I hope this won't be a problem.

**Comment by jekram** [comment]
Thanks for the updated. Hope you do well in your exam.

**Comment by AsadUllahBinTahir** [comment]
Udemy course has been completed. 
I will upload the sample apps by Friday night IA.

**Comment by jekram** [comment]
Thanks. Do you need a server to load the sample apps?

**Comment by AsadUllahBinTahir** [comment]
No I will upload the rar files here in comments for you to review.

Today I studied half of the 6th chapter and worked on a sample bugs. I also did some testing with Imran and Sojharo.

**Comment by jekram** [comment]
Thanks for the update

**Comment by AsadBinTahir** [comment]
Today I first completed the remaining part of the book's 6th chapter and completed the 7th chapter along with it. 
I also worked on my remaining udemy course sample apps and completed them.

In one of the apps, parse server was used by stephen grider and the company no longer provide that service. I am looking for its alternative. So a part of functionality related to parse server is not working but the remaining does.

I could have attached the all of the app related work here in comment but the size of it is larger then the maximum file size.

**Comment by AsadBinTahir** [comment]
I will keep on working on the books sample apps and other react-native practice stuff, along with the other work if you assign some other job.

**Comment by jekram** [comment]
Thanks for the update.

**Comment by AsadBinTahir** [comment]
I studied chapter 8 and 9 from book, today. Chapter 9 was the overall overview of the previous concepts. I spent most of the time on it.
Two chapters have been left. Chapter 10 and 11 are about deployment to IOS store and android store respectively.
I will complete it on next working day.

**Comment by AsadBinTahir** [comment]
I completed the book as well. This issue can be closed now.

**Comment by jekram** [comment]
Thanks. Now let's focus of the building the debug tool
