### ISSUE TITLE
Learn ReactJS

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/Intern#24]
@AsadUllahBinTahir 

I think it would be best to learn ReactJS first before getting involved into React Native.

You will also find many online tutorials and blogs on ReactJs.

Please see:

https://facebook.github.io/react/

http://noeticforce.com/best-reactjs-tutorials-with-examples

There is an online tutorial on Udemy:  Modern React with Redux

The credentials for this course are here. 

https://docs.google.com/spreadsheets/d/1zR60sPGkvZVfTb98l4rPQ8-24mZVwV6xqxI2Flc72TI/edit#gid=0

If you have any question please let me know.

Coping @sojharo 

Let's target a week of time for the Udemy Class

**Comment by AsadUllahBinTahir** [comment]
I started learning React JS today. I have completed 20 lectures of Udemy. In the Udemy course, things are bit confusing for me. It was hard for me to grab the actual essence of React library. @sojharo has suggested me to go through Pro React book shared on google drive, along with the udemy course. From now on, I will also study the book. I hope I can enhance my understanding of react related things better this way. :)

**Comment by jekram** [comment]
Thanks for the update.

**Comment by jekram** [comment]
@AsadUllahBinTahir 

I have not seen any update here. What is the status

**Comment by AsadUllahBinTahir** [comment]
I am sorry I didn't inform you earlier about my exams at IBA. I would try to avoid such mistake in future. I will continue my ReactJS from tomorrow. Until now, I was struggling with ReactJS. I would do more effort in this regard to over come my deficiencies.

**Comment by jekram** [comment]
Asad communication is very important part of our life. Not just at work but other wise also. 

What is the struggle with ReactJS? It just needs your focus. If you need help ping Sojharo

**Comment by jekram** [comment]
Plus there is lot of online help available

**Comment by AsadUllahBinTahir** [comment]
Today I completed Section 2 of Udemy Course.

**Comment by AsadUllahBinTahir** [comment]
Today I completed Section 3 and 4 of the Udemy Course. I also studied first chapter of book React Pro (Which Sojharo gave me)

**Comment by jekram** [comment]
Thanks for the update

**Comment by AsadUllahBinTahir** [comment]
I have completed 72% of the Udemy React course. Also I studied some topics from chapter 2 of React Pro book.

**Comment by jekram** [comment]
Good job - Thanks

**Comment by AsadUllahBinTahir** [comment]
I have completed 81% of the udemy course.

**Comment by jekram** [comment]
Good job. Let's wrap this up and then you can go React Native (Mobile) IA

**Comment by AsadUllahBinTahir** [comment]
I have finished the Udemy Course. I am also studying the book and have gone through third chapter of the book. I will start React native from sunday.
This issue can be closed now.

**Comment by jekram** [comment]
Great job. You will enjoy React Native.
