### ISSUE TITLE
Learn ReactJS

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/Intern#25]
@ImranBinShoukat  

I think it would be best to learn ReactJS first before getting involved into React Native.

You will also find many online tutorials and blogs on ReactJs.

Please see:

https://facebook.github.io/react/

http://noeticforce.com/best-reactjs-tutorials-with-examples

There is an online tutorial on Udemy:  Modern React with Redux

The credentials for this course are here. 

https://docs.google.com/spreadsheets/d/1zR60sPGkvZVfTb98l4rPQ8-24mZVwV6xqxI2Flc72TI/edit#gid=0

If you have any question please let me know.

Coping @sojharo 

Let's target a week of time for the Udemy Class

**Comment by ImranBinShoukat** [comment]
I have started the "Modern React with Redux" course and watched the 23% of the video tutorials. Also @sojharo suggested us to go through the book 'Pro React', shared on the drive. So I have started to read the book too and covered the first chapter.

**Comment by jekram** [comment]
Thanks for the update

**Comment by jekram** [comment]
@ImranBinShoukat 
I have not seen any update here. What is the status

**Comment by jekram** [comment]
@ImranBinShoukat 

What is the update here? Do you not think you should update on the status.

Copy @sojharo

**Comment by ImranBinShoukat** [comment]
Sir, I am sorry for not updating it. I will continue this task today.

**Comment by ImranBinShoukat** [comment]
I have completed the 32% of the course.

**Comment by ImranBinShoukat** [comment]
Today, I continued the course and completed the 50% of the tutorials.

**Comment by jekram** [comment]
Great job !!!!! Thanks

**Comment by ImranBinShoukat** [comment]
Today, I watched more tutorials and completed the 75% of the course.

**Comment by jekram** [comment]
Thanks for the update.

**Comment by ImranBinShoukat** [comment]
I continued the course today and watched 83% of the tutorials.

**Comment by jekram** [comment]
Great. When you get done with this w would start you on React Native. The mobile platform and you would have great learning.

**Comment by ImranBinShoukat** [comment]
I have completed the course. Although I am still reading the book and read the 2nd chapter today as well but you can close this issue. I will start the React Native course from Sunday. Along with that I will continue reading the book and hopefully I will read  it by next Sunday.

**Comment by jekram** [comment]
Great job. Thanks for the update.

Please start with React Native. You would enjoy it.
