### ISSUE TITLE
 Test Cloudkibo URL April 04 

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/Intern#26]
@ImranBinShoukat 

Please retest:

1. In your testing please make sure one person is behind Proxy server (see @sojharo  for it).

In the browser to browser testing do not test /webmeeting only /conference
In Chrome to Firefox do not test Screen sharing

2. Also add test iOS to /conference please see @sumairasaeed for it. Only 1-1 session needs to be tested (Chrome to iOS & Android to iOS)

3. Also add test Android to /conference please see @sojharo for it. Only 1-1 session needs to be tested (Chrome to Android & Android to iOS)

![image](https://cloud.githubusercontent.com/assets/5336012/13099945/a55fb312-d4ec-11e5-9c64-a055b767a213.png)

FYI to @zarmeen92 @sojharo @AsadUllahBinTahir

**Comment by jekram** [comment]
any update?

**Comment by jekram** [comment]
@ImranBinShoukat 

What is the update here? Do you not think you should update on the status.

Copy @sojharo

**Comment by ImranBinShoukat** [comment]
I am sorry for not updating here. I will test it today.

**Comment by ImranBinShoukat** [comment]
I have tested the Chrome to iOS 1-1 conference call and here is the update:

![chrome to ios](https://cloud.githubusercontent.com/assets/17005430/14503697/a4dfa68a-01ca-11e6-99d1-9ca2d6690e4b.JPG)

**Comment by ImranBinShoukat** [comment]
We couldn't test the browser to browser conference today, because it needs a person behind the proxy but we all were on IBA's network and Sojharo didn't have the internet device.

**Comment by ImranBinShoukat** [comment]
I'll test the remaining on Friday.

**Comment by ImranBinShoukat** [comment]
Today, @sojharo forgot to bring the internet device and we couldn't test the browser to browser conference. Also in Android testing @sojharo said that there is some migration problem due to which we can't test the Android too.

**Comment by jekram** [comment]
Thanks for the update

**Comment by jekram** [comment]
Good job. Closing this and open a new task to test for this week.
