### ISSUE TITLE
Learn Wordpress

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/Intern#5]
Learn Wordpress

Please create a plan on how you can learn WordPress. As a next step detail out next steps.

**Comment by jekram** [comment]
Please watch these:

https://www.youtube.com/watch?v=sd0grLQ4voU
https://www.youtube.com/channel/UCvG9V9e1s2lN-hoWeHsDCJQ
https://www.youtube.com/watch?v=8Jv47_VIBOQ
https://www.youtube.com/watch?v=Oiov0L4blIw
https://www.youtube.com/watch?v=mFnKu3-n-HI
https://www.youtube.com/watch?v=mxphj0U5BGc

Later I will send you credentails so you can practice host a site to practice. It is critical that you practice and not just watch Video.

**Comment by AsadUllahBinTahir** [comment]
Today I watched the first tutorial about setting up a complete website using WordPress. I also tested the WebMeeting with Imran.

**Comment by jekram** [comment]
Thanks for the update.

Please let me know when I should get you an hosting site. So you can play Wordpress it will give you a better training.

**Comment by AsadUllahBinTahir** [comment]
It would be far better if I practice along with watching tutorials instead of practicing after watching all the videos. You can provide me hosting site as soon as possible.

**Comment by jekram** [comment]
Asad I sentbthr hosting credentials earlier did you get it

**Comment by jekram** [comment]
This was already sent to you. Confirm please
________________________________

**Comment by AsadUllahBinTahir** [comment]
Today I first installed LAMP on my droplet. Then I installed WordPress with the default theme. I'll modify the theme/Website tomorrow. Learning of installing the LAMP on droplet was also included in today's tasks.

**Comment by AsadUllahBinTahir** [comment]
http://192.241.177.175/

is the address of theme. 
Login credentials are:

User Name: jekram
Password: kibo4321

**Comment by jekram** [comment]
Thanks for the update.

**Comment by jekram** [comment]
Should I get you Wordpress Book or Wordpress Video training?

**Comment by AsadUllahBinTahir** [comment]
It would be helpful for me in case I get additional learning resources.

**Comment by jekram** [comment]
Ok. I will buy a book which has PDF version available and send it you Insha Allah today.

**Comment by jekram** [comment]
Here we go It is sitting on our Google drive. Please confirm if you can access it. It has book, supplement, and templates

https://drive.google.com/drive/folders/0ByXJY8WVZm-NVERfOU9lUElvZ3M

**Comment by AsadUllahBinTahir** [comment]
Today I watched another full tutorial of setting up WordPress website. I installed the theme on WordPress and customized it according to required style. I used CSS styles to override the default theme styles. Some pages are still to be modified which I would do tomorrow. Besides this, learning about different widgets and plugins was also included in today's learning tasks.

Thank you for the additional resources. Yes I can access these. It would surely enhance my web skills. :)

**Comment by jekram** [comment]
Asad one of my primary goal is that both of you learn new skills.

**Comment by AsadUllahBinTahir** [comment]
Today I added the remaining web pages to the hostel website. I also customized their CSS styles according to requirement. Addition of all the pages to the website is completed now. 
Also tested the Kibo support Issues and studied the PHP rules to redirect the web page in web server. I will start the wordpress book from tomorrow and continue my WordPress practice/experimentation.

**Comment by jekram** [comment]
Thanks for the update.

**Comment by AsadUllahBinTahir** [comment]
http://192.241.177.175/

Above is the link to modified Website.

**Comment by jekram** [comment]
Good job

**Comment by jekram** [comment]
@AsadUllahBinTahir  How is the training coming along?  How far are you into the book?

I

**Comment by AsadUllahBinTahir** [comment]
@jekram : Updated you about my training in email.

**Comment by jekram** [comment]
@AsadUllahBinTahir  Please let me know when you will be done on Wordpress training. As a next step, I want you to get Web Development training, but we would not start that until Wordpress training is done.

**Comment by AsadUllahBinTahir** [comment]
@jekram : I have watched the video tutorials and studied 1-3 & Plugins chapter in the WordPress book. Due to not having a PHP background, Sojharo asked me to skim through the theme designing/Rss feed chapters. 
I can now setup a website properly provided I am given with a theme. Customization of theme to according to requirement is also part of my skill set now. I think I am pretty ready to go for Web Development Training now. :)

**Comment by AsadUllahBinTahir** [comment]
I have also started learning angularjs 2 as per instructed by Sojharo.

**Comment by jekram** [comment]
@AsadUllahBinTahir 

I have bought an online course:

https://www.udemy.com/the-web-developer-bootcamp/

You should have received an invite for it.

I am going to close this Word Press task.
