### ISSUE TITLE
Learn Wordpress  

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/Intern#6]
Learn Wordpress

Please create a plan on how you can learn WordPress. As a next step detail out next steps.

**Comment by jekram** [comment]
Please watch these:  

https://www.youtube.com/watch?v=sd0grLQ4voU
https://www.youtube.com/channel/UCvG9V9e1s2lN-hoWeHsDCJQ
https://www.youtube.com/watch?v=8Jv47_VIBOQ
https://www.youtube.com/watch?v=Oiov0L4blIw
https://www.youtube.com/watch?v=mFnKu3-n-HI
https://www.youtube.com/watch?v=mxphj0U5BGc

Later  I will send you credentails so you can practice  host a site to practice. It is critical that you practice and not just watch Video.

**Comment by ImranBinShoukat** [comment]
I have watched the first video today. It would be great if you upload the credentials so we can practice as well.

**Comment by jekram** [comment]
@ImranBinShoukat 

Give me a day and I will send the credentials.

**Comment by ImranBinShoukat** [comment]
Today, I installed LAMP on my Droplet first. Then installed WordPress with the default theme.
You can check it here.
http://162.243.4.147/

I'll start modifying the theme/website from tomorrow.

**Comment by jekram** [comment]
Thanks for the update.

Please share userid and password

**Comment by ImranBinShoukat** [comment]
UserID: jekram
Pwd: kibo4321

**Comment by jekram** [comment]
Should I get you Wordpress Book or Wordpress Video training?

**Comment by ImranBinShoukat** [comment]
Yes it would be helpful.

**Comment by jekram** [comment]
Ok. I will buy a book today that has PDF version available also and Insha Allah will send it you today.

**Comment by jekram** [comment]
Here we go It is sitting on our Google drive. Please confirm if you can access it. It has book, supplement, and templates

https://drive.google.com/drive/folders/0ByXJY8WVZm-NVERfOU9lUElvZ3M

**Comment by ImranBinShoukat** [comment]
Today, I installed the theme and customized it. I also learnt the different widgets and plugins and watched the second video of setting up WordPress website. Some pages still to be modified which I will do tomorrow. 

 I am unable to access the book. It shows me the message that "The open folder can no longer to be viewed."

**Comment by jekram** [comment]
Imran you should have the same access as Asad. It should be available to every body with cloudkibo account. Please login into imran@cloudkibo.com and then try to access it. Let me know if it does not work..

Date: Wed, 10 Feb 2016 13:08:28 -0800

**Comment by ImranBinShoukat** [comment]
Yesterday, I tested the web-meeting, Login and screen sharing functionality and further modified the WordPress website. 
Today, I tested the web-meeting & conference functionality and read the WordPress book.

**Comment by jekram** [comment]
@ImranBinShoukat  This thread is about learning wordpress. It is easy for me if we keep the status to that thread only. 

Cloudkibo at http://162.243.4.147/  looks good.

How far are you in the book? How is the overall learning on Word Press going?

**Comment by ImranBinShoukat** [comment]
I have been through the videos and now I can setup/customize the themes. Besides this I am also studying the book very keenly.

**Comment by jekram** [comment]
@ImranBinShoukat  Thanks for the update.

**Comment by jekram** [comment]
@ImranBinShoukat  Please let me know when you will be done on Wordpress training. As a next step, I want you to get Web Development training, but we would not start that until Wordpress training is done.

**Comment by ImranBinShoukat** [comment]
I have studied first 3 and Plugins chapter in the book. I have skimmed through the other chapters because of the php. Other than that I have watched the video tutorials as well.

Now I can setup a website with the provided theme and customize it according to the requirements. So, I think I am pretty much done WordPress. 

I have also started to learn Angularjs2 as instructed by Sojharo.

**Comment by jekram** [comment]
@ImranBinShoukat 

I am going to close this task. You can always go back and learn more on Wordpress.
