### ISSUE TITLE
CloudKibo testing when there is a change

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/Intern#7]
@ImranBinShoukat 

Please watch CloudKibo chages so you are aware of any changes that are happening on CloudKibo.

![image](https://cloud.githubusercontent.com/assets/5336012/12877730/10e03552-cdcd-11e5-885e-41cb0c3f5f0c.png)

Then I would like to retest CloudKibo. NOT the whole CloudKibo but just focus on:

https://api.cloudkibo.com/#/conference/xyz   
https://api.cloudkibo.com/#/webconconference/xyz

**Comment by ImranBinShoukat** [comment]
Acknowledged.
