### ISSUE TITLE
KiboSupport testing when there is a change

### ISSUE THREAD

**Issue by jekram** [Cloudkibo/Intern#8]
@AsadUllahBinTahir 

Please watch KiboSupport so you are aware of any changes that are happening on KiboSupport.

![image](https://cloud.githubusercontent.com/assets/5336012/12877902/8e0503c6-cdcf-11e5-8d94-c249a15c338b.png)

I would like you to retest KiboSupport when there is a change.

**Comment by AsadUllahBinTahir** [comment]
I am already watching KiboSupport. I will retest the KiboSupport whenever a change would be made.
