### ISSUE TITLE
Webmeeting has been tested

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/Intern#9]
We tested the webmeeting function today and we found out that blank messages' error has been resolved. Chrome to Firefox and Firefox to Firefox screen sharing is also working. Video glitch error has also been resolved. 

There were still some errors which are:
1. In Firefox, the UI is broken.
2. The uploading gateway doesn't close once the downloading/uploading is aborted.
3. File transfer while previous transfer is still in progress.
4. Video should be shown when we are sharing screen.

**Comment by jekram** [comment]
@ImranBinShoukat @AsadUllahBinTahir 

It would be great if besides providing status on this thread you update the original issue thread with your comments. Also like in the past if there is a new issue please do not hesitate to open them.

Examples: (where issues have been fixed)

1. Blank message is fixed. Update the issue and say you have validated it.
2. Chrome to FireFox and FireFox to FireFox. Update the issue that you have validated it.
3. Video glitch error. Same as above.

If these issues were previously reported and are still open, there is NO need to update the status. If any one of these was not reported then please open an issue.


There were still some errors which are:
1. In Firefox, the UI is broken.
2. The uploading gateway doesn't close once the downloading/uploading is aborted.
3. File transfer while previous transfer is still in progress.
4. Video should be shown when we are sharing screen.

Thanks

Jawaid
